import type { Database } from '../types';
import {
  NEW_EXERCISE_SEEDS,
  MEDIA_UPDATE_EXISTING,
  ARCHIVE_EXISTING_IDS,
} from '../seed/v028ExerciseMediaLibrary';

/**
 * v028 — Exercise media library bundling (Free Exercise DB curation).
 *
 * Lands the curated 230-exercise media library (ADR-0017 Q8 media population)
 * reconciled against the 66 existing built-in seeds (grill 2026-06-24,
 * "C 折衷 + 只留 3 個獨有"):
 *
 *   1. INSERT 206 curated-only exercises (new stable exId(67..272)).
 *      `media_path` = Free-Exercise-DB folder key (→ EXERCISE_MEDIA require map)
 *      for the 143 with real photos; NULL for the 63 placeholders.
 *   2. UPDATE media_path on 24 same-name built-ins (give the existing row its
 *      real photo — keeps the id so user history/templates stay intact).
 *   3. UPDATE is_archived=1 on 39 existing-only built-ins superseded by the
 *      curated equipment-specific variants (FK-safe: rows survive for old
 *      sessions, just hidden from the picker).
 *   4. 3 existing-only built-ins (山羊挺身 / 板凳撐體 / 驢式提踵) are genuinely
 *      not in the curated set → left active, no change.
 *
 * Net active built-in library: 233 (24 reused + 206 new + 3 kept).
 *
 * NO fine-grained exercise_muscle mapping for the 206 new exercises — the
 * curation only resolved muscle_group, not primary/secondary muscles. Their
 * detail-page anatomy heatmap shows the muscle group only until a later pass
 * backfills muscle links. The 24 reused keep their v006 muscle mapping.
 *
 * load_type derivation (no UI-level weight prompt for bodyweight): equip='自重'
 * or a （自重）suffix → bodyweight; （輔助）→ assisted; else loaded. Best-effort —
 * the curation did not systematically tag load_type (only 13/230 set). A few
 * untagged bodyweight movements may read 'loaded'; refine later if it bites.
 *
 * Idempotent: INSERT OR IGNORE (stable ids) + UPDATE-by-id. Re-run is a no-op.
 *
 * Seed data is GENERATED by docs/exercise-media-import/build_seed.py from
 * docs/exercise-media-import/curated-master.json — re-run that to regenerate
 * both this migration's seed (v028ExerciseMediaLibrary.ts) and the require map
 * (exerciseMediaMap.ts) after editing the curated master.
 *
 * Cross-ADR: ADR-0017 (Exercise Library v2 — media population amendment).
 */
export async function v028_exercise_media_library(db: Database): Promise<void> {
  // 1: INSERT 206 curated-only exercises.
  for (const ex of NEW_EXERCISE_SEEDS) {
    await db.runAsync(
      `INSERT OR IGNORE INTO exercise
         (id, name, load_type, is_builtin, is_custom, muscle_group_id, equipment, media_path)
       VALUES (?, ?, ?, 1, 0, ?, ?, ?)`,
      ex.id,
      ex.name,
      ex.load_type,
      ex.muscle_group_id,
      ex.equipment,
      ex.media_key
    );
  }

  // 2: Give 24 same-name built-ins their real photo (preserve id).
  for (const [exerciseId, mediaKey] of MEDIA_UPDATE_EXISTING) {
    await db.runAsync(
      'UPDATE exercise SET media_path = ? WHERE id = ?',
      mediaKey,
      exerciseId
    );
  }

  // 3: Archive 39 existing-only built-ins superseded by curated variants.
  for (const exerciseId of ARCHIVE_EXISTING_IDS) {
    await db.runAsync(
      'UPDATE exercise SET is_archived = 1 WHERE id = ?',
      exerciseId
    );
  }
}
