import type { Database } from '../types';
import { EXERCISE_MUSCLE_LINKS } from '../seed/v029ExerciseMuscleLinks';

/**
 * v029 — fine-grained exercise_muscle links for the v028 curated library.
 *
 * DATA-ONLY migration (no schema change): the v028 curation inserted 206 new
 * built-in exercises (exId 67..272) carrying only `muscle_group_id`, so their
 * detail-page body diagram fell back to lighting the whole muscle GROUP
 * (groupFallbackHighlight). This back-fills the precise primary/secondary
 * `exercise_muscle` rows derived from Free-Exercise-DB, so resolveExerciseHighlight
 * prefers the fine links and the diagram lights the exact muscles.
 *
 * Scope: ONLY the 143 of 206 new exercises that have a media_key (= FE-DB folder
 * id). The 63 placeholders (media_key NULL) have no FE-DB data → no links → they
 * keep the group fallback. The 66 built-ins and 24 reused already have v006 links
 * and are untouched.
 *
 * Seed data is GENERATED by docs/exercise-media-import/build_muscle_links.py from
 * v028ExerciseMediaLibrary.ts + Free-Exercise-DB exercises.json. Re-run that to
 * regenerate src/db/seed/v029ExerciseMuscleLinks.ts.
 *
 * Primary-wins: the seed lists all primary rows before all secondary rows, and
 * INSERT OR IGNORE on the PK (exercise_id, muscle_id) silently drops a would-be
 * secondary that collides with an already-inserted primary (mirrors v006).
 *
 * Idempotent: INSERT OR IGNORE on the PK → re-run is a no-op.
 *
 * Cross-ADR: ADR-0017 (Exercise Library v2). ADR-0010 (muscle layer / taxonomy).
 */
export async function v029_exercise_muscle_links(db: Database): Promise<void> {
  for (const link of EXERCISE_MUSCLE_LINKS) {
    await db.runAsync(
      `INSERT OR IGNORE INTO exercise_muscle (exercise_id, muscle_id, role)
       VALUES (?, ?, ?)`,
      link.exercise_id,
      link.muscle_id,
      link.role
    );
  }
}
