/**
 * v028 seed — Exercise media library bundling (Free Exercise DB curation).
 *
 * GENERATED by docs/exercise-media-import/build_seed.py from curated-master.json.
 * Do not hand-edit; re-run the generator after editing curated-master.json.
 *
 * Reconciliation (grill 2026-06-24, C 折衷 + 只留 3 獨有):
 *   - NEW_EXERCISE_SEEDS    : 206 curated-only → INSERT new exId(67..272).
 *   - MEDIA_UPDATE_EXISTING : 24 同名 → UPDATE media_path on existing built-in id.
 *   - ARCHIVE_EXISTING_IDS  : 39 existing-only superseded → is_archived = 1.
 *   - 3 existing-only kept active (no media): 山羊挺身 / 板凳撐體 / 驢式提踵.
 *
 * media_key is the Free-Exercise-DB folder id = key into EXERCISE_MEDIA
 * (src/db/seed/exerciseMediaMap.ts). NULL = placeholder (hash-color thumb).
 */
import { type Equipment } from '../../domain/exercise/types';

export interface ExerciseMediaSeed {
  id: string;
  /** zh name (all new entries; en display is resolved via i18n en.exercise). */
  name: string;
  load_type: 'loaded' | 'bodyweight' | 'assisted';
  muscle_group_id: string;
  equipment: Equipment;
  /** key into EXERCISE_MEDIA; null = placeholder. */
  media_key: string | null;
}

export const NEW_EXERCISE_SEEDS: ReadonlyArray<ExerciseMediaSeed> = [
  { id: '00000000-0000-4000-8000-000000000043', name: '槓鈴前蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Front_Barbell_Squat' },
  { id: '00000000-0000-4000-8000-000000000044', name: '槓鈴弓箭步', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Barbell_Lunge' },
  { id: '00000000-0000-4000-8000-000000000045', name: '槓鈴硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Barbell_Deadlift' },
  { id: '00000000-0000-4000-8000-000000000046', name: '槓鈴羅馬尼亞硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Romanian_Deadlift' },
  { id: '00000000-0000-4000-8000-000000000047', name: '槓鈴相撲硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Sumo_Deadlift' },
  { id: '00000000-0000-4000-8000-000000000048', name: '槓鈴直腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Stiff-Legged_Barbell_Deadlift' },
  { id: '00000000-0000-4000-8000-000000000049', name: '早安式體前屈', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Good_Morning' },
  { id: '00000000-0000-4000-8000-00000000004a', name: '窄握槓鈴臥推', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '槓鈴', media_key: 'Close-Grip_Barbell_Bench_Press' },
  { id: '00000000-0000-4000-8000-00000000004b', name: '站姿槓鈴肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: 'Barbell_Shoulder_Press' },
  { id: '00000000-0000-4000-8000-00000000004c', name: '坐姿槓鈴肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: 'Seated_Barbell_Military_Press' },
  { id: '00000000-0000-4000-8000-00000000004d', name: '站姿軍事推舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: 'Standing_Military_Press' },
  { id: '00000000-0000-4000-8000-00000000004e', name: '借力推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: 'Push_Press' },
  { id: '00000000-0000-4000-8000-00000000004f', name: '槓鈴直立划船', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: 'Upright_Barbell_Row' },
  { id: '00000000-0000-4000-8000-000000000050', name: '反握划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '槓鈴', media_key: 'Reverse_Grip_Bent-Over_Rows' },
  { id: '00000000-0000-4000-8000-000000000051', name: 'T槓划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '槓鈴', media_key: 'T-Bar_Row_with_Handle' },
  { id: '00000000-0000-4000-8000-000000000052', name: '槓鈴仰臥拉舉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '槓鈴', media_key: 'Bent-Arm_Barbell_Pullover' },
  { id: '00000000-0000-4000-8000-000000000053', name: '牧師彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '槓鈴', media_key: 'Preacher_Curl' },
  { id: '00000000-0000-4000-8000-000000000054', name: '反握槓鈴彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '槓鈴', media_key: 'Reverse_Barbell_Curl' },
  { id: '00000000-0000-4000-8000-000000000055', name: '槓鈴顱骨粉碎', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '槓鈴', media_key: 'Lying_Close-Grip_Barbell_Triceps_Extension_Behind_The_Head' },
  { id: '00000000-0000-4000-8000-000000000056', name: '槓鈴臀推', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '槓鈴', media_key: 'Barbell_Hip_Thrust' },
  { id: '00000000-0000-4000-8000-000000000057', name: '槓鈴臀橋', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '槓鈴', media_key: 'Barbell_Glute_Bridge' },
  { id: '00000000-0000-4000-8000-000000000058', name: '站姿槓鈴提踵', load_type: 'loaded', muscle_group_id: 'mg-calf', equipment: '槓鈴', media_key: 'Standing_Barbell_Calf_Raise' },
  { id: '00000000-0000-4000-8000-000000000059', name: '槓鈴滾輪捲腹', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '槓鈴', media_key: 'Barbell_Ab_Rollout' },
  { id: '00000000-0000-4000-8000-00000000005a', name: '坐姿槓鈴腕彎舉', load_type: 'loaded', muscle_group_id: 'mg-forearm', equipment: '槓鈴', media_key: 'Seated_Palm-Up_Barbell_Wrist_Curl' },
  { id: '00000000-0000-4000-8000-00000000005b', name: '下斜啞鈴臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '啞鈴', media_key: 'Decline_Dumbbell_Bench_Press' },
  { id: '00000000-0000-4000-8000-00000000005c', name: '上斜啞鈴飛鳥', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '啞鈴', media_key: 'Incline_Dumbbell_Flyes' },
  { id: '00000000-0000-4000-8000-00000000005d', name: '啞鈴仰臥拉舉', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '啞鈴', media_key: 'Bent-Arm_Dumbbell_Pullover' },
  { id: '00000000-0000-4000-8000-00000000005e', name: '坐姿啞鈴肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Seated_Dumbbell_Press' },
  { id: '00000000-0000-4000-8000-00000000005f', name: '阿諾肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Arnold_Dumbbell_Press' },
  { id: '00000000-0000-4000-8000-000000000060', name: '啞鈴側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Side_Lateral_Raise' },
  { id: '00000000-0000-4000-8000-000000000061', name: '啞鈴前平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Front_Dumbbell_Raise' },
  { id: '00000000-0000-4000-8000-000000000062', name: '俯身後束飛鳥', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Reverse_Flyes' },
  { id: '00000000-0000-4000-8000-000000000063', name: '上斜啞鈴彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '啞鈴', media_key: 'Incline_Dumbbell_Curl' },
  { id: '00000000-0000-4000-8000-000000000064', name: '集中彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '啞鈴', media_key: 'Concentration_Curls' },
  { id: '00000000-0000-4000-8000-000000000065', name: 'Zottman 彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '啞鈴', media_key: 'Zottman_Curl' },
  { id: '00000000-0000-4000-8000-000000000066', name: '臥姿啞鈴三頭伸展', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '啞鈴', media_key: 'Lying_Dumbbell_Tricep_Extension' },
  { id: '00000000-0000-4000-8000-000000000067', name: '站姿過頭啞鈴三頭伸展', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '啞鈴', media_key: 'Standing_Dumbbell_Triceps_Extension' },
  { id: '00000000-0000-4000-8000-000000000068', name: '啞鈴三頭後屈伸', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '啞鈴', media_key: 'Tricep_Dumbbell_Kickback' },
  { id: '00000000-0000-4000-8000-000000000069', name: '坐姿啞鈴三頭推', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '啞鈴', media_key: 'Seated_Triceps_Press' },
  { id: '00000000-0000-4000-8000-00000000006a', name: '啞鈴深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Dumbbell_Squat' },
  { id: '00000000-0000-4000-8000-00000000006b', name: '啞鈴弓箭步', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Dumbbell_Lunges' },
  { id: '00000000-0000-4000-8000-00000000006c', name: '啞鈴登階', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Dumbbell_Step_Ups' },
  { id: '00000000-0000-4000-8000-00000000006d', name: '啞鈴相撲深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Plie_Dumbbell_Squat' },
  { id: '00000000-0000-4000-8000-00000000006e', name: '啞鈴分腿蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Split_Squat_with_Dumbbells' },
  { id: '00000000-0000-4000-8000-00000000006f', name: '單臂啞鈴划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '啞鈴', media_key: 'One-Arm_Dumbbell_Row' },
  { id: '00000000-0000-4000-8000-000000000070', name: '啞鈴直腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: 'Stiff-Legged_Dumbbell_Deadlift' },
  { id: '00000000-0000-4000-8000-000000000071', name: '站姿啞鈴提踵', load_type: 'loaded', muscle_group_id: 'mg-calf', equipment: '啞鈴', media_key: 'Standing_Dumbbell_Calf_Raise' },
  { id: '00000000-0000-4000-8000-000000000072', name: '啞鈴體側屈', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '啞鈴', media_key: 'Dumbbell_Side_Bend' },
  { id: '00000000-0000-4000-8000-000000000073', name: '史密斯臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '史密斯機', media_key: 'Smith_Machine_Bench_Press' },
  { id: '00000000-0000-4000-8000-000000000074', name: '史密斯上斜臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '史密斯機', media_key: 'Smith_Machine_Incline_Bench_Press' },
  { id: '00000000-0000-4000-8000-000000000075', name: '史密斯窄握臥推', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '史密斯機', media_key: 'Smith_Machine_Close-Grip_Bench_Press' },
  { id: '00000000-0000-4000-8000-000000000076', name: '史密斯深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: 'Smith_Machine_Squat' },
  { id: '00000000-0000-4000-8000-000000000077', name: '史密斯肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '史密斯機', media_key: 'Smith_Machine_Overhead_Shoulder_Press' },
  { id: '00000000-0000-4000-8000-000000000078', name: '史密斯直立划船', load_type: 'loaded', muscle_group_id: 'mg-trap', equipment: '史密斯機', media_key: 'Smith_Machine_Upright_Row' },
  { id: '00000000-0000-4000-8000-000000000079', name: '史密斯划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '史密斯機', media_key: 'Smith_Machine_Bent_Over_Row' },
  { id: '00000000-0000-4000-8000-00000000007a', name: '史密斯提踵', load_type: 'loaded', muscle_group_id: 'mg-calf', equipment: '史密斯機', media_key: 'Smith_Machine_Calf_Raise' },
  { id: '00000000-0000-4000-8000-00000000007b', name: '寬握滑輪下拉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'Wide-Grip_Lat_Pulldown' },
  { id: '00000000-0000-4000-8000-00000000007c', name: '窄握滑輪下拉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'Close-Grip_Front_Lat_Pulldown' },
  { id: '00000000-0000-4000-8000-00000000007d', name: 'V 把下拉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'V-Bar_Pulldown' },
  { id: '00000000-0000-4000-8000-00000000007e', name: '反握滑輪下拉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'Underhand_Cable_Pulldowns' },
  { id: '00000000-0000-4000-8000-00000000007f', name: '直臂下壓', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'Straight-Arm_Pulldown' },
  { id: '00000000-0000-4000-8000-000000000080', name: '單臂坐姿滑輪划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: 'Seated_One-arm_Cable_Pulley_Rows' },
  { id: '00000000-0000-4000-8000-000000000081', name: '滑輪直立划船', load_type: 'loaded', muscle_group_id: 'mg-trap', equipment: '滑輪', media_key: 'Upright_Cable_Row' },
  { id: '00000000-0000-4000-8000-000000000082', name: '滑輪後束飛鳥', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'Cable_Rear_Delt_Fly' },
  { id: '00000000-0000-4000-8000-000000000083', name: '坐姿滑輪側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'Cable_Seated_Lateral_Raise' },
  { id: '00000000-0000-4000-8000-000000000084', name: '直桿三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Triceps_Pushdown' },
  { id: '00000000-0000-4000-8000-000000000085', name: '繩索三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Triceps_Pushdown_-_Rope_Attachment' },
  { id: '00000000-0000-4000-8000-000000000086', name: '繩索過頭臂屈伸', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Cable_Rope_Overhead_Triceps_Extension' },
  { id: '00000000-0000-4000-8000-000000000087', name: '滑輪夾胸', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '滑輪', media_key: 'Cable_Crossover' },
  { id: '00000000-0000-4000-8000-000000000088', name: '低位滑輪夾胸', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '滑輪', media_key: 'Low_Cable_Crossover' },
  { id: '00000000-0000-4000-8000-000000000089', name: '站姿滑輪推胸', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '滑輪', media_key: 'Standing_Cable_Chest_Press' },
  { id: '00000000-0000-4000-8000-00000000008a', name: '滑輪二頭彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '滑輪', media_key: 'Standing_Biceps_Cable_Curl' },
  { id: '00000000-0000-4000-8000-00000000008b', name: '繩索錘式彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '滑輪', media_key: 'Cable_Hammer_Curls_-_Rope_Attachment' },
  { id: '00000000-0000-4000-8000-00000000008c', name: '滑輪牧師彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '滑輪', media_key: 'Cable_Preacher_Curl' },
  { id: '00000000-0000-4000-8000-00000000008d', name: '滑輪跪姿捲腹', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '滑輪', media_key: 'Cable_Crunch' },
  { id: '00000000-0000-4000-8000-00000000008e', name: '滑輪砍柴', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '滑輪', media_key: 'Standing_Cable_Wood_Chop' },
  { id: '00000000-0000-4000-8000-00000000008f', name: '滑輪聳肩', load_type: 'loaded', muscle_group_id: 'mg-trap', equipment: '滑輪', media_key: 'Cable_Shrugs' },
  { id: '00000000-0000-4000-8000-000000000090', name: '滑輪前後拉', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '滑輪', media_key: 'Pull_Through' },
  { id: '00000000-0000-4000-8000-000000000091', name: '滑輪後踢腿', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '滑輪', media_key: 'One-Legged_Cable_Kickback' },
  { id: '00000000-0000-4000-8000-000000000092', name: '腿推', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Leg_Press' },
  { id: '00000000-0000-4000-8000-000000000093', name: '坐姿腿屈伸', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Leg_Extensions' },
  { id: '00000000-0000-4000-8000-000000000094', name: '哈克深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Hack_Squat' },
  { id: '00000000-0000-4000-8000-000000000095', name: '俯臥腿彎舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Lying_Leg_Curls' },
  { id: '00000000-0000-4000-8000-000000000096', name: '坐姿腿彎舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Seated_Leg_Curl' },
  { id: '00000000-0000-4000-8000-000000000097', name: '蝴蝶機夾胸', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '固定機械', media_key: 'Butterfly' },
  { id: '00000000-0000-4000-8000-000000000098', name: '機械肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '固定機械', media_key: 'Machine_Shoulder_Military_Press' },
  { id: '00000000-0000-4000-8000-000000000099', name: '反向蝴蝶機後束', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '固定機械', media_key: 'Reverse_Machine_Flyes' },
  { id: '00000000-0000-4000-8000-00000000009a', name: '機械高位划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: 'Leverage_High_Row' },
  { id: '00000000-0000-4000-8000-00000000009b', name: '機械坐姿划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: 'Leverage_Iso_Row' },
  { id: '00000000-0000-4000-8000-00000000009c', name: '機械二頭彎舉', load_type: 'loaded', muscle_group_id: 'mg-bicep', equipment: '固定機械', media_key: 'Machine_Bicep_Curl' },
  { id: '00000000-0000-4000-8000-00000000009d', name: '機械三頭伸展', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '固定機械', media_key: 'Machine_Triceps_Extension' },
  { id: '00000000-0000-4000-8000-00000000009e', name: '機械臂屈伸', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '固定機械', media_key: 'Dip_Machine' },
  { id: '00000000-0000-4000-8000-00000000009f', name: '機械蹬式提踵', load_type: 'loaded', muscle_group_id: 'mg-calf', equipment: '固定機械', media_key: 'Calf_Press' },
  { id: '00000000-0000-4000-8000-0000000000a0', name: '機械捲腹', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '固定機械', media_key: 'Ab_Crunch_Machine' },
  { id: '00000000-0000-4000-8000-0000000000a1', name: '坐姿腿外展', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '固定機械', media_key: 'Thigh_Abductor' },
  { id: '00000000-0000-4000-8000-0000000000a2', name: '坐姿腿內收', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '固定機械', media_key: 'Thigh_Adductor' },
  { id: '00000000-0000-4000-8000-0000000000a3', name: '壺鈴擺盪', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '壺鈴', media_key: 'One-Arm_Kettlebell_Swings' },
  { id: '00000000-0000-4000-8000-0000000000a4', name: '壺鈴高腳杯深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '壺鈴', media_key: 'Goblet_Squat' },
  { id: '00000000-0000-4000-8000-0000000000a5', name: '雙壺鈴前蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '壺鈴', media_key: 'Front_Squats_With_Two_Kettlebells' },
  { id: '00000000-0000-4000-8000-0000000000a6', name: '壺鈴單腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '壺鈴', media_key: 'Kettlebell_One-Legged_Deadlift' },
  { id: '00000000-0000-4000-8000-0000000000a7', name: '壺鈴肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '壺鈴', media_key: 'Two-Arm_Kettlebell_Military_Press' },
  { id: '00000000-0000-4000-8000-0000000000a8', name: '壺鈴上膊', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '壺鈴', media_key: 'One-Arm_Kettlebell_Clean' },
  { id: '00000000-0000-4000-8000-0000000000a9', name: '壺鈴抓舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '壺鈴', media_key: 'One-Arm_Kettlebell_Snatch' },
  { id: '00000000-0000-4000-8000-0000000000aa', name: '壺鈴推蹲', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '壺鈴', media_key: 'Kettlebell_Thruster' },
  { id: '00000000-0000-4000-8000-0000000000ab', name: '單臂壺鈴划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '壺鈴', media_key: 'One-Arm_Kettlebell_Row' },
  { id: '00000000-0000-4000-8000-0000000000ac', name: '壺鈴地板臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '壺鈴', media_key: 'One-Arm_Kettlebell_Floor_Press' },
  { id: '00000000-0000-4000-8000-0000000000ad', name: '壺鈴風車', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '壺鈴', media_key: 'Kettlebell_Windmill' },
  { id: '00000000-0000-4000-8000-0000000000ae', name: '土耳其起立', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '壺鈴', media_key: 'Kettlebell_Turkish_Get-Up_Squat_style' },
  { id: '00000000-0000-4000-8000-0000000000af', name: '架上臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '槓鈴', media_key: 'Pin_Presses' },
  { id: '00000000-0000-4000-8000-0000000000b0', name: '坐姿機械推胸（上胸）', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '固定機械', media_key: 'Leverage_Incline_Chest_Press' },
  { id: '00000000-0000-4000-8000-0000000000b1', name: '坐姿機械推胸（下胸）', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '固定機械', media_key: 'Leverage_Decline_Chest_Press' },
  { id: '00000000-0000-4000-8000-0000000000b2', name: '坐姿機械推胸（平胸）', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '固定機械', media_key: 'Leverage_Chest_Press' },
  { id: '00000000-0000-4000-8000-0000000000b3', name: '單側滑輪夾胸', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '滑輪', media_key: 'Single-Arm_Cable_Crossover' },
  { id: '00000000-0000-4000-8000-0000000000b4', name: '雙槓臂屈伸（自重）', load_type: 'bodyweight', muscle_group_id: 'mg-chest', equipment: '自重', media_key: 'Dips_-_Chest_Version' },
  { id: '00000000-0000-4000-8000-0000000000b5', name: '伏地挺身（上斜）', load_type: 'bodyweight', muscle_group_id: 'mg-chest', equipment: '自重', media_key: 'Incline_Push-Up' },
  { id: '00000000-0000-4000-8000-0000000000b6', name: '伏地挺身（下斜）', load_type: 'bodyweight', muscle_group_id: 'mg-chest', equipment: '自重', media_key: 'Decline_Push-Up' },
  { id: '00000000-0000-4000-8000-0000000000b7', name: '暫停臥推', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000b8', name: '雙槓臂屈伸（輔助）', load_type: 'assisted', muscle_group_id: 'mg-chest', equipment: '自重', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000b9', name: '雙槓臂屈伸（負重）', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '自重', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ba', name: '蝴蝶機夾胸（上胸）', load_type: 'loaded', muscle_group_id: 'mg-chest', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000bb', name: '引體向上（自重）', load_type: 'bodyweight', muscle_group_id: 'mg-back', equipment: '自重', media_key: 'Pullups' },
  { id: '00000000-0000-4000-8000-0000000000bc', name: '引體向上（輔助）', load_type: 'assisted', muscle_group_id: 'mg-back', equipment: '自重', media_key: 'Band_Assisted_Pull-Up' },
  { id: '00000000-0000-4000-8000-0000000000bd', name: '引體向上（負重）', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '自重', media_key: 'Weighted_Pull_Ups' },
  { id: '00000000-0000-4000-8000-0000000000be', name: '潘德雷划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000bf', name: '機械高位划船（反握）', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c0', name: '機械單側高位划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c1', name: '機械單側高位划船（反握）', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c2', name: '機械單側划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c3', name: '對握滑輪下拉', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c4', name: '單臂直臂下壓', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c5', name: '坐姿划船（寬握）', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c6', name: '六角槓划船', load_type: 'loaded', muscle_group_id: 'mg-back', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000c7', name: '澤奇深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Zercher_Squats' },
  { id: '00000000-0000-4000-8000-0000000000c8', name: '槓鈴箱蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Box_Squat' },
  { id: '00000000-0000-4000-8000-0000000000c9', name: '史密斯分腿蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: 'Smith_Single-Leg_Split_Squat' },
  { id: '00000000-0000-4000-8000-0000000000ca', name: '坐姿腿屈伸（單腿）', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: 'Single-Leg_Leg_Extension' },
  { id: '00000000-0000-4000-8000-0000000000cb', name: '六角槓硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Trap_Bar_Deadlift' },
  { id: '00000000-0000-4000-8000-0000000000cc', name: '槓鈴抓舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: 'Snatch' },
  { id: '00000000-0000-4000-8000-0000000000cd', name: '架上深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ce', name: '槓鈴單腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000cf', name: '槓鈴分腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d0', name: 'SSB深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d1', name: 'SSB箱蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d2', name: '槓鈴分腿蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d3', name: 'SSB分腿蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d4', name: '史密斯澤奇深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d5', name: '史密斯硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d6', name: '史密斯單腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d7', name: '史密斯分腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d8', name: '史密斯羅馬尼亞硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000d9', name: '史密斯弓箭步', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '史密斯機', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000da', name: '腿推（單腿）', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000db', name: '俯臥腿彎舉（單腿）', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000dc', name: '坐姿腿彎舉（單腿）', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000dd', name: '啞鈴高腳杯深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000de', name: '啞鈴羅馬尼亞硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000df', name: '啞鈴單腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e0', name: '啞鈴分腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e1', name: '地雷管硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e2', name: '地雷管羅馬尼亞硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e3', name: '地雷管單腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e4', name: '地雷管分腿硬舉', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e5', name: '六角槓深蹲', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e6', name: '六角槓箭步走', load_type: 'loaded', muscle_group_id: 'mg-leg', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e7', name: '啞鈴臀推', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e8', name: '啞鈴單腿臀推', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000e9', name: '滑輪側踢腿', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ea', name: '機械後踢腿', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000eb', name: '機械側踢腿', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ec', name: '啞鈴側弓箭步', load_type: 'loaded', muscle_group_id: 'mg-glute', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ed', name: '槓片前平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '其他', media_key: 'Front_Plate_Raise' },
  { id: '00000000-0000-4000-8000-0000000000ee', name: '啞鈴單側坐姿肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Dumbbell_One-Arm_Shoulder_Press' },
  { id: '00000000-0000-4000-8000-0000000000ef', name: '滑輪單側側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'Standing_Low-Pulley_Deltoid_Raise' },
  { id: '00000000-0000-4000-8000-0000000000f0', name: '滑輪肩外旋', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'External_Rotation_with_Cable' },
  { id: '00000000-0000-4000-8000-0000000000f1', name: '滑輪肩內旋', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'Cable_Internal_Rotation' },
  { id: '00000000-0000-4000-8000-0000000000f2', name: '滑輪前平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: 'Front_Cable_Raise' },
  { id: '00000000-0000-4000-8000-0000000000f3', name: '啞鈴後束肩旋', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: 'Reverse_Flyes_With_External_Rotation' },
  { id: '00000000-0000-4000-8000-0000000000f4', name: '啞鈴單側跪姿肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000f5', name: '槓片單側跪姿肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '其他', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000f6', name: '槓鈴暫停肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000f7', name: '槓鈴架上肩推', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '槓鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000f8', name: '站姿滑輪側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000f9', name: '滑輪單邊後束飛鳥', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000fa', name: '機械側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000fb', name: '坐姿啞鈴前平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000fc', name: '啞鈴單邊後束肩旋', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000fd', name: '半俯身側平舉', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000fe', name: '蝴蝶機單側後束飛鳥', load_type: 'loaded', muscle_group_id: 'mg-shoulder', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-0000000000ff', name: 'V-bar三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Triceps_Pushdown_-_V-Bar_Attachment' },
  { id: '00000000-0000-4000-8000-000000000100', name: '反手直桿三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Reverse_Grip_Triceps_Pushdown' },
  { id: '00000000-0000-4000-8000-000000000101', name: '單側反手三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: 'Cable_One_Arm_Tricep_Extension' },
  { id: '00000000-0000-4000-8000-000000000102', name: '單側平板啞鈴臂屈伸', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '啞鈴', media_key: 'One_Arm_Pronated_Dumbbell_Triceps_Extension' },
  { id: '00000000-0000-4000-8000-000000000103', name: '單側繩索三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-000000000104', name: '單側三頭下壓', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-000000000105', name: '單側繩索過頭臂屈伸', load_type: 'loaded', muscle_group_id: 'mg-tricep', equipment: '滑輪', media_key: null },
  { id: '00000000-0000-4000-8000-000000000106', name: '坐姿槓鈴腕彎舉（反手）', load_type: 'loaded', muscle_group_id: 'mg-forearm', equipment: '槓鈴', media_key: 'Seated_Palms-Down_Barbell_Wrist_Curl' },
  { id: '00000000-0000-4000-8000-000000000107', name: '單臂手提箱深蹲', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '啞鈴', media_key: null },
  { id: '00000000-0000-4000-8000-000000000108', name: '捲腹（自重）', load_type: 'bodyweight', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Crunches' },
  { id: '00000000-0000-4000-8000-000000000109', name: '捲腹（負重）', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Weighted_Crunches' },
  { id: '00000000-0000-4000-8000-00000000010a', name: '懸掛抬腿（自重）', load_type: 'bodyweight', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Hanging_Leg_Raise' },
  { id: '00000000-0000-4000-8000-00000000010b', name: '懸掛抬腿（負重）', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '自重', media_key: null },
  { id: '00000000-0000-4000-8000-00000000010c', name: '機械側捲腹', load_type: 'loaded', muscle_group_id: 'mg-core', equipment: '固定機械', media_key: null },
  { id: '00000000-0000-4000-8000-00000000010d', name: '平躺抬腿', load_type: 'bodyweight', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Flat_Bench_Lying_Leg_Raise' },
  { id: '00000000-0000-4000-8000-00000000010e', name: '空中單車', load_type: 'bodyweight', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Air_Bike' },
  { id: '00000000-0000-4000-8000-00000000010f', name: '平板支撐', load_type: 'bodyweight', muscle_group_id: 'mg-core', equipment: '自重', media_key: 'Plank' },
  { id: '00000000-0000-4000-8000-000000000110', name: '坐姿槓片提踵', load_type: 'loaded', muscle_group_id: 'mg-calf', equipment: '其他', media_key: null },
];

/** [existing built-in id, media_key] — give a same-named built-in its real photo. */
export const MEDIA_UPDATE_EXISTING: ReadonlyArray<readonly [string, string]> = [
  ['00000000-0000-4000-8000-000000000002', 'Barbell_Squat'],
  ['00000000-0000-4000-8000-000000000016', 'Rack_Pulls'],
  ['00000000-0000-4000-8000-000000000001', 'Barbell_Bench_Press_-_Medium_Grip'],
  ['00000000-0000-4000-8000-000000000008', 'Barbell_Incline_Bench_Press_-_Medium_Grip'],
  ['00000000-0000-4000-8000-000000000009', 'Decline_Barbell_Bench_Press'],
  ['00000000-0000-4000-8000-000000000005', 'Bent_Over_Barbell_Row'],
  ['00000000-0000-4000-8000-00000000002e', 'Barbell_Curl'],
  ['00000000-0000-4000-8000-00000000002b', 'Barbell_Shrug'],
  ['00000000-0000-4000-8000-00000000000a', 'Dumbbell_Bench_Press'],
  ['00000000-0000-4000-8000-00000000000b', 'Incline_Dumbbell_Press'],
  ['00000000-0000-4000-8000-00000000000d', 'Dumbbell_Flyes'],
  ['00000000-0000-4000-8000-000000000025', 'Dumbbell_Shoulder_Press'],
  ['00000000-0000-4000-8000-00000000002f', 'Dumbbell_Bicep_Curl'],
  ['00000000-0000-4000-8000-000000000030', 'Hammer_Curls'],
  ['00000000-0000-4000-8000-000000000014', 'Bent_Over_Two-Dumbbell_Row'],
  ['00000000-0000-4000-8000-00000000002c', 'Dumbbell_Shrug'],
  ['00000000-0000-4000-8000-000000000012', 'Seated_Cable_Rows'],
  ['00000000-0000-4000-8000-00000000002d', 'Face_Pull'],
  ['00000000-0000-4000-8000-000000000042', 'Pallof_Press'],
  ['00000000-0000-4000-8000-00000000000f', 'Machine_Bench_Press'],
  ['00000000-0000-4000-8000-000000000039', 'Seated_Calf_Raise'],
  ['00000000-0000-4000-8000-000000000038', 'Standing_Calf_Raises'],
  ['00000000-0000-4000-8000-000000000007', 'Pushups'],
  ['00000000-0000-4000-8000-000000000040', 'Russian_Twist'],
];

/** existing built-in ids superseded by curated variants → is_archived = 1. */
export const ARCHIVE_EXISTING_IDS: ReadonlyArray<string> = [
  '00000000-0000-4000-8000-000000000013', // T 槓划船
  '00000000-0000-4000-8000-000000000033', // 三頭下壓
  '00000000-0000-4000-8000-000000000034', // 仰卧臂屈伸
  '00000000-0000-4000-8000-00000000001a', // 保加利亞分腿蹲
  '00000000-0000-4000-8000-000000000026', // 側平舉
  '00000000-0000-4000-8000-000000000027', // 前平舉
  '00000000-0000-4000-8000-000000000019', // 前蹲
  '00000000-0000-4000-8000-00000000003c', // 反向腕屈
  '00000000-0000-4000-8000-000000000015', // 反握引體向上
  '00000000-0000-4000-8000-00000000001e', // 弓箭步
  '00000000-0000-4000-8000-000000000006', // 引體向上
  '00000000-0000-4000-8000-000000000028', // 後束飛鳥
  '00000000-0000-4000-8000-00000000003f', // 懸吊舉腿
  '00000000-0000-4000-8000-00000000003e', // 捲腹
  '00000000-0000-4000-8000-00000000003d', // 棒式
  '00000000-0000-4000-8000-000000000011', // 滑輪下拉
  '00000000-0000-4000-8000-000000000031', // 牧師椅彎舉
  '00000000-0000-4000-8000-00000000002a', // 直立划船
  '00000000-0000-4000-8000-000000000023', // 相撲硬舉
  '00000000-0000-4000-8000-000000000003', // 硬舉
  '00000000-0000-4000-8000-000000000036', // 窄握臥推
  '00000000-0000-4000-8000-00000000000c', // 繩索夾胸
  '00000000-0000-4000-8000-000000000032', // 繩索彎舉
  '00000000-0000-4000-8000-000000000022', // 繩索後踢腿
  '00000000-0000-4000-8000-000000000041', // 繩索斜砍
  '00000000-0000-4000-8000-000000000024', // 羅馬尼亞硬舉
  '00000000-0000-4000-8000-000000000004', // 肩推
  '00000000-0000-4000-8000-00000000003b', // 腕屈
  '00000000-0000-4000-8000-00000000001c', // 腿伸展
  '00000000-0000-4000-8000-00000000001d', // 腿彎舉
  '00000000-0000-4000-8000-00000000001b', // 腿推機
  '00000000-0000-4000-8000-000000000020', // 臀推
  '00000000-0000-4000-8000-000000000021', // 臀橋
  '00000000-0000-4000-8000-000000000018', // 輔助引體向上
  '00000000-0000-4000-8000-000000000010', // 輔助雙槓臂屈伸
  '00000000-0000-4000-8000-000000000035', // 過頭三頭伸展
  '00000000-0000-4000-8000-000000000029', // 阿諾推舉
  '00000000-0000-4000-8000-00000000000e', // 雙槓臂屈伸
  '00000000-0000-4000-8000-00000000001f', // 高腳杯深蹲
];
