/**
 * v029 seed-integrity — PURE coverage of the generated `EXERCISE_MUSCLE_LINKS`
 * seed array, with NO migration / DB round-trip.
 *
 * The shipped `tests/db/v029_exercise_muscle_links.test.ts` exercises the
 * MIGRATION (row counts, FK sanity, spot anchors, idempotence) but verifies
 * the *seed data itself* only loosely (length 556, keyed⊆linked, one GLOBAL
 * "last primary < first secondary" check). The seed is GENERATED by
 * `build_muscle_links.py`; a generator regression that emits a typo'd muscle
 * id, a duplicate row, a stray link for a placeholder exercise, or a
 * secondary row ordered before its same-muscle primary WITHIN one exercise
 * would slip past most of those — INSERT OR IGNORE silently masks duplicates,
 * and the global ordering check can hold even when a single exercise's rows
 * are internally mis-ordered.
 *
 * These tests pin the seed's data-level invariants directly so a bad
 * regeneration fails fast, before it ever reaches a migration.
 */

import { EXERCISE_MUSCLE_LINKS } from '../../src/db/seed/v029ExerciseMuscleLinks';
import { NEW_EXERCISE_SEEDS } from '../../src/db/seed/v028ExerciseMediaLibrary';
import { MUSCLE_SEEDS } from '../../src/db/seed/v006ExerciseLibrary';

describe('v029 seed integrity (pure data, no migration)', () => {
  const CANONICAL_MUSCLE_IDS = new Set(MUSCLE_SEEDS.map((m) => m.id));
  const KEYED_EXERCISE_IDS = new Set(
    NEW_EXERCISE_SEEDS.filter((e) => e.media_key).map((e) => e.id)
  );

  it('every referenced muscle_id is one of the canonical 19-muscle taxonomy ids', () => {
    // Pins the seed's muscle vocabulary against the v006 source of truth
    // WITHOUT a DB. A generator that emits e.g. `m-quads` (typo) or a FE-DB
    // muscle name that was never mapped to our taxonomy would be caught here
    // — the migration's FK-orphan check only fires after INSERT, and only if
    // the bad id also happens to violate the FK; a pure check is stricter and
    // names the offenders.
    const unknown = [
      ...new Set(
        EXERCISE_MUSCLE_LINKS.filter((l) => !CANONICAL_MUSCLE_IDS.has(l.muscle_id)).map(
          (l) => l.muscle_id
        )
      ),
    ];
    expect(unknown).toEqual([]);
  });

  it('the seed exercises exactly the canonical muscle ids it is allowed to (subset, not equality)', () => {
    // Not every one of the 19 muscles must appear (e.g. an obscure muscle may
    // have no curated exercise), but the referenced set must be a SUBSET.
    const referenced = new Set(EXERCISE_MUSCLE_LINKS.map((l) => l.muscle_id));
    for (const id of referenced) {
      expect(CANONICAL_MUSCLE_IDS.has(id)).toBe(true);
    }
  });

  it('every linked exercise_id is a v028 NEW_EXERCISE_SEED that carries a media_key (linked ⊆ keyed)', () => {
    // The shipped test checks keyed ⊆ linked + size 143; this is the REVERSE
    // containment — no link may exist for a placeholder (media_key NULL) or a
    // non-existent / built-in exercise. A stray link would light a body
    // diagram for an exercise that ships no fine-grained activation.
    const stray = [
      ...new Set(
        EXERCISE_MUSCLE_LINKS.filter((l) => !KEYED_EXERCISE_IDS.has(l.exercise_id)).map(
          (l) => l.exercise_id
        )
      ),
    ];
    expect(stray).toEqual([]);
    // And the linked set is EXACTLY the 143 keyed exercises (both directions).
    const linked = new Set(EXERCISE_MUSCLE_LINKS.map((l) => l.exercise_id));
    expect(linked.size).toBe(143);
    expect(linked).toEqual(KEYED_EXERCISE_IDS);
  });

  it('has no exact-duplicate (exercise_id, muscle_id, role) rows', () => {
    // INSERT OR IGNORE would silently swallow exact dupes; the seed itself
    // must be clean so the 556 count is meaningful.
    const seen = new Set<string>();
    const dupes: string[] = [];
    for (const l of EXERCISE_MUSCLE_LINKS) {
      const key = `${l.exercise_id}|${l.muscle_id}|${l.role}`;
      if (seen.has(key)) dupes.push(key);
      seen.add(key);
    }
    expect(dupes).toEqual([]);
  });

  it('has no conflicting role for the same (exercise_id, muscle_id) pair', () => {
    // A muscle should never appear as BOTH primary and secondary for one
    // exercise in the seed. The migration's PK is (exercise_id, muscle_id) so
    // INSERT OR IGNORE keeps whichever row lands first — a seed that lists the
    // same pair twice with different roles is ambiguous and depends on row
    // order to resolve; forbid it outright.
    const roleByPair = new Map<string, Set<string>>();
    for (const l of EXERCISE_MUSCLE_LINKS) {
      const pair = `${l.exercise_id}|${l.muscle_id}`;
      const roles = roleByPair.get(pair) ?? new Set<string>();
      roles.add(l.role);
      roleByPair.set(pair, roles);
    }
    const conflicting = [...roleByPair.entries()]
      .filter(([, roles]) => roles.size > 1)
      .map(([pair]) => pair);
    expect(conflicting).toEqual([]);
  });

  it('within EVERY exercise, no secondary row precedes a same-exercise primary row (per-exercise ordering)', () => {
    // The shipped test only asserts a GLOBAL "last primary index < first
    // secondary index". That is a coincidence of generation order; the
    // load-bearing INSERT-OR-IGNORE contract is PER EXERCISE — for any one
    // exercise, all its primary rows must come before its secondary rows, so
    // a primary lands first and survives the IGNORE. Verify that locally.
    const offenders: string[] = [];
    const seenSecondaryFor = new Map<string, boolean>();
    // Walk in seed order, grouping by exercise as we go.
    for (const l of EXERCISE_MUSCLE_LINKS) {
      if (l.role === 'secondary') {
        seenSecondaryFor.set(l.exercise_id, true);
      } else if (l.role === 'primary' && seenSecondaryFor.get(l.exercise_id)) {
        // A primary appeared AFTER a secondary for the same exercise.
        offenders.push(l.exercise_id);
      }
    }
    expect([...new Set(offenders)]).toEqual([]);
  });

  it('every row has a valid role (primary | secondary) — no stray/empty role', () => {
    const badRoles = [
      ...new Set(
        EXERCISE_MUSCLE_LINKS.filter(
          (l) => l.role !== 'primary' && l.role !== 'secondary'
        ).map((l) => String(l.role))
      ),
    ];
    expect(badRoles).toEqual([]);
  });

  it('only the two documented abductor/adductor machines lack a PRIMARY row (taxonomy gap, not a bug)', () => {
    // Almost every linked exercise must carry a primary mover so its body
    // diagram lights something. The TWO exceptions are the seated thigh
    // abductor (坐姿腿外展) / adductor (坐姿腿內收) machines: FE-DB marks
    // abductors/adductors as the PRIMARY muscle, but our 19-muscle taxonomy
    // has no abductor/adductor muscle (per the 2026-06-24 C decision —
    // "abductor/adductor 無對應 → 不處理"), so the generator mapped only the
    // SECONDARY (glute/hamstring) muscles. Pinning the exact id set documents
    // the quirk and catches a regression where ANY OTHER exercise loses its
    // primary mover.
    const EXPECTED_SECONDARY_ONLY = new Set([
      '00000000-0000-4000-8000-0000000000a1', // 坐姿腿外展 (Thigh_Abductor)
      '00000000-0000-4000-8000-0000000000a2', // 坐姿腿內收 (Thigh_Adductor)
    ]);
    const hasPrimary = new Set(
      EXERCISE_MUSCLE_LINKS.filter((l) => l.role === 'primary').map((l) => l.exercise_id)
    );
    const missingPrimary = new Set(
      [...KEYED_EXERCISE_IDS].filter((id) => !hasPrimary.has(id))
    );
    expect(missingPrimary).toEqual(EXPECTED_SECONDARY_ONLY);
  });
});
